# Each entry: (identifier, file_name_in_item, bucket, artist, title, license_str)
PLAN = [
# ---------- meditation_relaxing ----------
("AmbientFourthWorldTromboneWorks", "AReallyNicePairOfBoltCutters.mp3", "meditation_relaxing", "jeff bernhardt", "A Really Nice Pair Of Bolt Cutters", "CC BY-SA 3.0"),
("AmbientFourthWorldTromboneWorks", "Equinox.mp3", "meditation_relaxing", "jeff bernhardt", "Equinox", "CC BY-SA 3.0"),
("dailyambient-2012", "Day-02_30-6.mp3", "meditation_relaxing", "R. Cole", "Daily Ambient - Day 02", "CC BY-SA 3.0"),
("dailyambient-2012", "Day-03_1-7.mp3", "meditation_relaxing", "R. Cole", "Daily Ambient - Day 03", "CC BY-SA 3.0"),
("Argiflex-Regolith", "01-Biomagnetism.mp3", "meditation_relaxing", "Curtis Lehr (Argiflex)", "Biomagnetism", "CC BY 3.0"),
("Argiflex-Regolith", "05-crystalSpheres.mp3", "meditation_relaxing", "Curtis Lehr (Argiflex)", "Crystal Spheres", "CC BY 3.0"),
("AmbientHaunt", "AmbientHaunt.mp3", "meditation_relaxing", "John D. Parker", "Ambient Haunt", "CC BY-SA 3.0"),
("jamendo-638405", "01-2326291-Megis-Theta Binaural Meditation.mp3", "meditation_relaxing", "Megis", "Theta Binaural Meditation", "CC BY 3.0"),
("jamendo-129318", "01-1085260-Val Davis-The Opening.mp3", "meditation_relaxing", "Val Davis", "The Opening", "CC BY 3.0"),
("jamendo-129318", "02-1085259-Val Davis-Awakening.mp3", "meditation_relaxing", "Val Davis", "Awakening", "CC BY 3.0"),
("jamendo-638091", "01-2325646-Megis-432Hz Quantum Healing Meditation.mp3", "meditation_relaxing", "Megis", "432Hz Quantum Healing Meditation", "CC BY 3.0"),
("jamendo-468945", "01-1915572-Sevennotes-Relaxing Soul Music.mp3", "meditation_relaxing", "Sevennotes", "Relaxing Soul Music", "CC BY 3.0"),
("jamendo-525353", "01-2037778-Moonwalk-Reflections _Meditative Drone Ambient_.mp3", "meditation_relaxing", "Moonwalk", "Reflections (Meditative Drone Ambient)", "CC BY 3.0"),
("jamendo-631043", "01-2313123-Tina Ambient-Ancient - Cinematic Drone.mp3", "meditation_relaxing", "Tina Ambient", "Ancient - Cinematic Drone", "CC BY 3.0"),
("jamendo-258390", "01-1517794-D.K.O. soundscape-Space Blow.mp3", "meditation_relaxing", "D.K.O. soundscape", "Space Blow", "CC BY-SA 3.0"),
("jamendo-125218", "01-1061091-Marcello Morgese-Mental Chaos.mp3", "meditation_relaxing", "Marcello Morgese", "Mental Chaos", "CC BY-SA 2.5"),
("jamendo-125218", "02-1061084-Marcello Morgese-War.mp3", "meditation_relaxing", "Marcello Morgese", "War", "CC BY-SA 2.5"),
# ---------- deep_house_yoga ----------
("jamendo-316588", "01-1432177-Jack Greenwood-Jack Greenwood - Scarlet Miracle _Original Mix__Deep House_.mp3", "deep_house_yoga", "Jack Greenwood", "Scarlet Miracle (Original Mix)", "CC BY 3.0"),
("jamendo-308829", "01-1432174-Jack Greenwood-Jack Greenwood - Infinity _Original Mix__Deep House_.mp3", "deep_house_yoga", "Jack Greenwood", "Infinity (Original Mix)", "CC BY 3.0"),
("jamendo-321006", "01-1432179-Jack Greenwood-Jack Greenwood - Take It Easy _Original Mix__Deep House_.mp3", "deep_house_yoga", "Jack Greenwood", "Take It Easy (Original Mix)", "CC BY 3.0"),
("jamendo-323018", "01-1432180-Jack Greenwood-Jack Greenwood - The Chain of Events _Original Mix__Deep House_.mp3", "deep_house_yoga", "Jack Greenwood", "The Chain of Events (Original Mix)", "CC BY 3.0"),
("jamendo-324925", "01-1432181-Jack Greenwood-Jack Greenwood - Wake Me Up _Original Mix__Deep House_.mp3", "deep_house_yoga", "Jack Greenwood", "Wake Me Up (Original Mix)", "CC BY 3.0"),
("jamendo-216657", "01-1377417-Mast-Never say  _Deep House_ _Original mix_.mp3", "deep_house_yoga", "Mast", "Never Say (Original Mix)", "CC BY 3.0"),
("jamendo-302460", "01-1380903-RasL-RasL-Deep_house_music.mp3", "deep_house_yoga", "RasL", "Deep House Music", "CC BY-SA 3.0"),
("jamendo-331822", "01-1478109-Jaros-Yoga.mp3", "deep_house_yoga", "Jaros", "Yoga", "CC BY 3.0"),
# ---------- triphop_downtempo ----------
("jamendo-124355", "01-1054964-Faces in the clouds-Man must explore.mp3", "triphop_downtempo", "Faces in the clouds", "Man Must Explore", "CC BY-SA 3.0"),
("jamendo-124355", "02-1054965-Faces in the clouds-Sea of darkness.mp3", "triphop_downtempo", "Faces in the clouds", "Sea Of Darkness", "CC BY-SA 3.0"),
("jamendo-526099", "01-2037538-Moonwalk-Lazy Sunday _Chill Downtempo Beat_.mp3", "triphop_downtempo", "Moonwalk", "Lazy Sunday (Chill Downtempo Beat)", "CC BY 3.0"),
("jamendo-526100", "01-2037540-Moonwalk-Soothing Soundscapes _Chill Downtempo Beat_.mp3", "triphop_downtempo", "Moonwalk", "Soothing Soundscapes (Chill Downtempo Beat)", "CC BY 3.0"),
("jamendo-525295", "01-2037721-Moonwalk-Downtempo Delights _Lofi Hip-hop_.mp3", "triphop_downtempo", "Moonwalk", "Downtempo Delights (Lofi Hip-hop)", "CC BY 3.0"),
("jamendo-510444", "01-2004372-Sevennotes-Modern Downtempo.mp3", "triphop_downtempo", "Sevennotes", "Modern Downtempo", "CC BY 3.0"),
("jamendo-461257", "01-1898500-Sevennotes-Beauty Ambient Downtempo.mp3", "triphop_downtempo", "Sevennotes", "Beauty Ambient Downtempo", "CC BY 3.0"),
("CelyGrande-RelaxationchilloutHip-hopInstrumental", "CelyGrande-RelaxationchilloutHip-hopInstrumental.mp3", "triphop_downtempo", "Cely Grande", "Relaxation (Chillout Hip-Hop Instrumental)", "CC0 1.0"),
("IdmLoopy", "Kidjazz-IdmLoopy.mp3", "triphop_downtempo", "kidjazz", "IDM Loopy", "CC BY-SA 3.0"),
("TripHopTricks", "TripHopTricks.mp3", "triphop_downtempo", "My Free Mickey", "Trip Hop Tricks", "CC BY-SA 3.0"),
("RenaissanceByAinst.Idm", "AinstClub-Child_2011.mp3", "triphop_downtempo", "Ainst", "Child", "CC0 1.0"),
("RenaissanceByAinst.Idm", "AinstClub-Ep1_2011.mp3", "triphop_downtempo", "Ainst", "Ep1", "CC0 1.0"),
# ---------- liquid_dnb ----------
("rz279", "01_Keda_Kid-72.mp3", "liquid_dnb", "Keda Kid", "72", "CC BY 3.0"),
("rz279", "02_Keda_Kid-Arcane.mp3", "liquid_dnb", "Keda Kid", "Arcane", "CC BY 3.0"),
("rz279", "03_Keda_Kid-Clear_Nuclear.mp3", "liquid_dnb", "Keda Kid", "Clear Nuclear", "CC BY 3.0"),
("jamendo-551981", "01-2138496-Steven Booth-Runaway Drum n Bass by Steven Booth.mp3", "liquid_dnb", "Steven Booth", "Runaway Drum n Bass", "CC BY 3.0"),
("jamendo-134963", "01-1127329-Arnaud Dromigny-Jungle Train.mp3", "liquid_dnb", "Arnaud Dromigny", "Jungle Train", "CC BY-SA 3.0"),
("jamendo-120776", "01-1027142-Dj89-Dj89 Feat Candy89 - effet miroir _ drum and bass_ mix.mp3", "liquid_dnb", "Dj89 feat Candy89", "Effet Miroir (Drum And Bass Mix)", "CC BY-SA 3.0"),
("jamendo-188268", "02-1692557-Guizmoliveset-adrumandbass.mp3", "liquid_dnb", "Guizmoliveset", "A Drum And Bass", "CC BY-SA 3.0"),
("jamendo-188268", "04-1692555-Guizmoliveset-H drum and bassj.mp3", "liquid_dnb", "Guizmoliveset", "H Drum And Bass", "CC BY-SA 3.0"),
]
